list_movie_names = [
    "Monarch: Legacy of Monsters", "Onimusha", "The Family Business", "The Night Agent", "Deadpool 3",
    "Who Is Erin Carter?", "Captain Laserhawk: A Blood Dragon Remix", "Kraven the Hunter", "Helluva Boss", "Boudica",
    "Ballerina", "Hypnotic", "Sultan of Delhi", "Sisu", "Gladiator 2", "Argylle", "The Retirement Plan",
    "Heart of Stone",
    "Twisted Metal", "The Beekeeper", "Masters of the Air", "Rise of the Footsoldier: Vengeance",
    "Lego Marvel Avengers: Code Red",
    "Percy Jackson and the Olympians", "Avatar: The Last Airbender", "Kandahar", "Baldur's Gate III", "Gangs of London",
    "The Monster Squad", "Deep Fear", "Desperation Road", "To Catch a Killer", "Justice League: Warworld",
    "The Machine",
    "Ragnarok", "Strong Girl Nam-soon", "The Negotiator", "The Terminal List", "The Out-Laws",
    "Spider-Man: Beyond the Spider-Verse",
    "Khufiya", "Captain America: Brave New World", "Iraivan", "FUBAR", "Cyberpunk: Edgerunners", "Invincible: Atom Eve",
    "Concrete Utopia", "Godzilla x Kong: The New Empire", "The Legend of Vox Machina", "Spy Game", "Chainsaw Man",
    "The Lazarus Project", "Rabbit Hole", "The Toxic Avenger", "Mission: Impossible - Dead Reckoning Part Two",
    "Silent Night",
    "Commando", "Those Who Wish Me Dead", "Ghost", "None", "Scott Pilgrim Takes Off", "Blade",
    "The Banana Splits Movie",
    "None", "None", "Paradise", "Alan Wake", "Magnum Force", "SAS Rogue Heroes", "Muzzle", "Arthdal Chronicles", "None",
    "Daredevil: Born Again", "Unhinged", "Zathura: A Space Adventure", "Hidden Strike", "Citadel",
    "Avengers: The Kang Dynasty",
    "Tiger 3", "None", "None", "None", "Fear the Night", "Thunderbolts", "The Mother", "Robyn Hood", "Curses!",
    "Polite Society",
    "Migration", "None", "None", "God Is a Bullet", "None", "Fallen", "Fallout: New Vegas", "Renegades",
    "El Camino: A Breaking Bad Movie", "Young Guns", "Wayne", "None", "The Nevers", "In the Shadow of the Moon",
    "Aarya", "Furiosa",
    "King of Killers", "Bloodthirst", "The Winchesters", "Homefront", "The Marksman", "Fantastic Four", "None", "None",
    "Journey 2: The Mysterious Island", "SAS: Red Notice", "Deep Impact", "The Enforcer",
    "Spartacus: Gods of the Arena", "Oldboy",
    "The Quarry", "None", "New York Ninja", "In the Land of Saints and Sinners", "Run Hide Fight",
    "Sympathy for the Devil",
    "Dracula 2001", "The Misfits", "Mafia Mamma", "Fate: The Winx Saga", "The Acolyte", "None", "Joy Ride",
    "Six Days Seven Nights",
    "Shrapnel", "None", "Game Night", "Undead Unluck", "Ganapath: Hero is Born", "Copshop", "Drive-Away Dolls", "None",
    "Mission Raniganj", "Jailer", "The Commuter", "The Batman Part II", "Lockwood & Co.", "The Man in the Iron Mask",
    "Journey to the Center of the Earth", "Goblin Slayer", "Bombay My Beloved", "Vikram", "Dragged Across Concrete",
    "None",
    "Superman: Legacy", "The Freelancer", "U-571", "Boss Level", "Spy Kids: Armageddon", "The Three Musketeers"
]

list_movie_genre = [
    ["Action", "Adventure", "Sci-Fi"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Crime", "Drama"],
    [],
    ["Action", "Drama", "Thriller"],
    ["Action", "Comedy", "Sci-Fi"],
    ["Action", "Adventure", "Crime"],
    ["Animation", "Action", "Adventure"],
    [],
    ["Action", "Adventure", "Sci-Fi"],
    ["Animation", "Action", "Comedy"],
    ["Action", "Drama", "History"],
    ["Action", "Thriller"],
    ["Action", "Mystery", "Thriller"],
    ["Action", "Drama"],
    ["Action", "War"],
    ["Action", "Drama", "Adventure"],
    ["Action", "Thriller"],
    ["Action", "Comedy", "Crime"],
    ["Action", "Crime", "Thriller"],
    ["Action", "Adventure", "Comedy"],
    ["Action", "Thriller"],
    ["Action", "Drama", "Thriller"],
    [],
    ["Action"],
    ["Animation", "Action", "Adventure"],
    ["Family", "Action", "Adventure"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Thriller"],
    ["Action", "Adventure", "Fantasy"],
    ["Action", "Crime", "Drama"],
    ["Action", "Comedy", "Fantasy"],
    ["Action", "Thriller"],
    ["Action", "Mystery", "Thriller"],
    ["Action", "Crime", "Drama"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Comedy"],
    [],
    [],
    ["Action", "Drama", "Fantasy"],
    ["Action", "Comedy", "Crime"],
    ["Action", "Crime", "Drama"],
    ["Action", "Crime", "Drama"],
    ["Comedy", "Crime", "Drama"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Biography", "Crime"],
    ["Action", "Adventure", "Sci-Fi"],
    ["Action", "Crime", "Drama"],
    ["Action", "Adventure", "Comedy"],
    ["Animation", "Action", "Adventure"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Adventure", "Drama"],
    ["Action", "Adventure", "Sci-Fi"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Crime", "Thriller"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Drama", "Fantasy"],
    ["Action", "Drama", "Thriller"],
    ["Action", "Comedy", "Horror"],
    ["Action", "Comedy", "Horror"],
    ["Action", "Drama", "Fantasy"],
    ["Action", "Drama", "Thriller"],
    ["Action", "Comedy", "Horror"],
    ["Action", "Adventure", "Thriller"],
    ["Action", "Drama", "Thriller"],
    ["Drama", "Fantasy", "Romance"],
    [],
    ["Animation", "Action", "Adventure"],
    ["Action", "Fantasy", "Horror"],
    ["Action", "Comedy", "Horror"],
    [],
    [],
    ["Action", "Sci-Fi", "Thriller"],
    ["Action", "Adventure", "Horror"],
    ["Action", "Crime", "Mystery"],
    ["Action", "Drama", "Thriller"],
    ["Action", "Crime", "Thriller"],
    ["Action", "Drama", "Fantasy"],
    [],
    ["Action", "Adventure", "Crime"],
    ["Action", "Thriller"],
    ["Action", "Adventure", "Comedy"],
    [],
    ["Action", "Drama", "Thriller"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Biography", "Crime"],
    ["Action", "Adventure", "Sci-Fi"],
    ["Action", "Crime", "Drama"],
    ["Action", "Adventure", "Comedy"],
    ["Animation", "Action", "Adventure"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Adventure", "Drama"],
    ["Action", "Crime", "Thriller"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Drama", "Fantasy"],
    ["Action", "Comedy", "Crime"],
    ["Action", "Crime", "Drama"],
    ["Action", "Crime", "Drama"],
    ["Action", "Crime", "Thriller"],
    ["Action", "Adventure", "Comedy"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Biography", "Drama"],
    ["Action", "Comedy", "Thriller"],
    ["Action", "Drama", "Sci-Fi"],
    ["Action", "Thriller"],
    ["Action", "Comedy", "Thriller"],
    [],
    ["Action", "Biography", "Drama"],
    ["Action", "Comedy", "Crime"],
    ["Action", "Mystery", "Thriller"],
    ["Action", "Crime", "Drama"],
    ["Action", "Adventure", "Drama"],
    ["Action", "Adventure", "Drama"],
    ["Action", "Adventure", "Family"],
    ["Animation", "Action", "Adventure"],
    ["Action", "Comedy", "Crime"],
    ["Action", "Crime", "Thriller"],
    ["Action", "Crime", "Drama"],
    ["Action", "Adventure", "Comedy"],
    ["Action", "Comedy", "Family"],
    ["Action", "Adventure", "Horror"]
]
